// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import SupabaseAuthProvider from "@/components/providers/SupabaseAuthProvider";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, IBM_Plex_Mono, Noto_Serif } from "next/font/google";
import "./globals.css";
const fontSans = Geist({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: "100"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased overflow-x-hidden`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SupabaseAuthProvider>
            {children}
            <Toaster richColors />
          </SupabaseAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}