// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import SupabaseAuthProvider from "@/components/providers/SupabaseAuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import { Manrope, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const fontSans = Manrope({ subsets: ["latin"], variable: "--font-sans" });

const fontHeading = Source_Sans_3({ subsets: ["latin"], variable: "--font-heading" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={fontSans.variable + " " + fontHeading.variable}
    >
      <body className="antialiased overflow-x-hidden">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <TooltipProvider>
            <SupabaseAuthProvider>
              <QueryProvider>
                {children}
                <Toaster richColors />
              </QueryProvider>
            </SupabaseAuthProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
